### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/web-ext-tab-manager#1]
- [x] new repository for tab manager extension
  - https://github.com/hi-ogawa/web-ext-tab-manager
- [x] polish style
  - https://github.com/hi-ogawa/web-ext-vite-template/pull/10
- [x] export/import
  - https://github.com/hi-ogawa/web-ext-vite-template/pull/12
- [ ] #11
- [x] #10
- [ ] #12
  - https://developer.chrome.com/docs/webstore/about_webstore/
  - https://github.com/hi-ogawa/web-ext-vite-template/pull/9
  - a bit annoying to prepare screenshots with exact size `1280x800 or 640x400`
- [ ] workaround for manifest v3 during dev (probably none exists)
  - https://github.com/hi-ogawa/web-ext-vite-template/issues/3
- [ ] use `browser.bookmarks` as a storage?

**Comment by hi-ogawa** [comment]
<details><summary>example data for quick testing/screenshot</summary>

```json
{
  "groups": [
    {
      "createdAt": "2023-02-19T04:07:42.184Z",
      "tabs": [
        {
          "url": "https://www.youtube.com/watch?v=M4IXtSTBy-0",
          "title": "夢の中に連れてって - 東京女子流 12th Anniversary Live 物語の1ページ ～キミと きっと ずっと～ - - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/b95ddd88/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=o4XoiEUlq0o&list=RDGMEMhCgTQvcskbGUxqI4Sn2QYw&index=2",
          "title": "つばきファクトリー『スキップ・スキップ・スキップ』Promotion Edit - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/b95ddd88/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=Km71Rr9K-Bw&list=RDGMEM0s70dY0AfCwh3LqQ-Bv1xgVMsVTy_wmn5SU&index=4",
          "title": "NewJeans (뉴진스) 'Ditto' Performance Video - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/b95ddd88/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=jv-blLXJ9uc",
          "title": "CYNHN「キリグニア」Music Video - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/b95ddd88/img/favicon_32x32.png"
        }
      ]
    },
    {
      "createdAt": "2023-02-18T09:54:42.422Z",
      "tabs": [
        {
          "url": "https://www.youtube.com/watch?v=72vOux51-o4",
          "title": "Jacob Collier feat. Jonah Nilsson - Do I Do (Live) | Montreux Jazz Festival 2017 - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/b95ddd88/img/favicon_32x32.png"
        }
      ]
    },
    {
      "createdAt": "2023-02-12T08:25:08.245Z",
      "tabs": [
        {
          "url": "https://www.youtube.com/watch?v=gx7Krkf3t2k",
          "title": "Cory Wong // Live at First Avenue FEB 2022 - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://github.com/hi-ogawa/web-ext-vite-template",
          "title": "hi-ogawa/web-ext-vite-template",
          "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg"
        },
        {
          "url": "https://github.com/hi-ogawa/web-ext-vite-template/pull/9",
          "title": "chore: use manifest v3 for production by hi-ogawa · Pull Request #9 · hi-ogawa/web-ext-vite-template",
          "favIconUrl": "https://github.githubassets.com/favicons/favicon-success.svg"
        }
      ]
    },
    {
      "createdAt": "2023-02-11T12:39:29.447Z",
      "tabs": [
        {
          "url": "https://www.youtube.com/watch?v=gx7Krkf3t2k",
          "title": "Cory Wong // Live at First Avenue FEB 2022 - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        }
      ]
    },
    {
      "createdAt": "2023-02-11T12:29:20.139Z",
      "tabs": [
        {
          "url": "https://www.youtube.com/watch?v=8lWoKIYp4Fo",
          "title": "【MV】Shiritsu Ebisu Chugaku”Seishun Zombies” - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=Ilu3Q1iSKh8&list=RDMM&index=4",
          "title": "2022.10.27 synchrotoron タワーレコード秋葉原店 リリースイベント my room (アコースティック ver.) 【期間限定】 - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=VVeEYOebeBQ",
          "title": "フィロソフィーのダンス/ライブ・ライフ - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=KY2lWN7JsSw",
          "title": "VULFPECK /// Simple Step - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=Olgj0UbVZuw&list=RDGMEMhCgTQvcskbGUxqI4Sn2QYwVMvNR6uICic8c&index=16",
          "title": "【ライブ】イート・ザ・大目玉 Live at 私立恵比寿中学 バンドのみんなと大学芸会2019 エビ中のフルバッテリー・サラウンド - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=W5ZbTCldUIg&list=RDGMEMhCgTQvcskbGUxqI4Sn2QYwVMCjvpYUSNNHM&index=6",
          "title": "DEAR KISS 「ハッピー」 MUSIC VIDEO - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        },
        {
          "url": "https://www.youtube.com/watch?v=xBf3VqVKS9U&list=RDMM&index=4",
          "title": "宮本佳林『なんてったって I Love You』Promotion Edit - YouTube",
          "favIconUrl": "https://www.youtube.com/s/desktop/5191a190/img/favicon_32x32.png"
        }
      ]
    }
  ]
}
```

</details>
